name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Linting

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Pnpm install
        run: pnpm install

      - name: Lint
        run: |
          cd lint-configs && pnpm lint
          cd ../test && pnpm lint

      - name: Test
        if: ${{ !cancelled() }}
        working-directory: ./lint-configs
        run: pnpm test

  publish:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Publish package
        uses: JS-DevTools/npm-publish@v3
        with:
          package: ./lint-configs
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          provenance: true
